name: canvasbench-eval
dependencies:
  - _libgcc_mutex==0.1=main
  - _tflow_select==2.1.0=gpu
  - astor==0.8.1=py37_0
  - async_generator==1.10
  - cudatoolkit==9.0
  - cudnn==7.6.5=cuda9.0_0
  - cupti==9.0.176=0
  - decorator==4.4.2
  - defusedxml==0.6.0
  - gast==0.4.0
  - google-pasta==0.2.0
  - h5py==2.10.0
  - hdf5==1.10.6
  - importlib-metadata==2.0.0
  - importlib_metadata==2.0.0
  - intel-openmp==2020.2=254
  - ipykernel==5.3.4
  - ipython==5.8.0
  - ipython_genutils==0.2.0
  - jinja2==2.11.2
  - jsonschema==3.2.0
  - jupyter_client==6.1.7
  - jupyter_core==4.6.3
  - jupyterlab_pygments==0.1.2
  - keras-applications==1.0.8
  - keras-base==2.3.1=py37_0
  - keras-preprocessing==1.1.0=py_1
  - keras==2.3.1=0
  - ld_impl_linux-64==2.33.1
  - libedit==3.1.20191231
  - libffi==3.3
  - libgcc-ng==9.1.0
  - libgfortran-ng==7.3.0
  - libprotobuf==3.13.0.1
  - libsodium==1.0.18
  - libstdcxx-ng==9.1.0
  - lpips
  - markdown==3.3.2
  - markupsafe==1.1.1
  - mistune==0.8.4
  - mkl-service==2.3.0
  - mkl==2020.2=256
  - mkl_fft==1.2.0
  - mkl_random==1.1.1
  - nbclient==0.5.1
  - nbconvert==6.0.7
  - nbformat==5.0.8
  - ncurses==6.2
  - nest-asyncio==1.4.1
  - notebook==6.1.4
  - numpy==1.19.2
  - openssl==1.1.1h
  - packaging==20.4
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pillow
  - prometheus_client==0.8.0
  - prompt_toolkit==1.0.15
  - protobuf==3.13.0.1
  - ptyprocess==0.6.0
  - pycparser==2.20
  - pygments==2.7.2
  - pyparsing==2.4.7
  - pyrsistent==0.17.3
  - python-dateutil==2.8.1
  - python==3.7.9
  - pyyaml==5.3.1
  - pyzmq==19.0.2
  - readline==8.0
  - scikit-image
  - scipy==1.5.2
  - send2trash==1.5.0
  - setuptools==50.3.0
  - simplegeneric==0.8.1
  - six==1.15.0
  - sqlite==3.33.0
  - tensorboard==1.14.0
  - tensorflow-base==1.14.0
  - tensorflow-estimator==1.14.0
  - tensorflow-gpu==1.14.0
  - termcolor==1.1.0
  - terminado==0.9.1
  - testpath==0.4.4
  - tk==8.6.10
  - tornado==6.0.4
  - traitlets==5.0.5
  - wcwidth==0.2.5
  - webencodings==0.5.1
  - werkzeug==1.0.1
  - wheel==0.35.1
  - wrapt==1.12.1
  - xz==5.2.5
  - yaml==0.2.5
  - zeromq==4.3.3
  - zipp==3.4.0
  - zlib==1.2.11
prefix: /home/seooyxx/miniconda3/envs/canvasbench-eval
