agent_type: single_modification

benchmark_dir: ../dataset/benchmarks/modification_gt
results_dir: ../dataset/results/modification_gen/single_canvas
batches_config_path: ../dataset/batches/modification/batches.yaml

channels:
  channel_1:
    api_base_url: http://localhost:3001
  channel_2:
    api_base_url: 
  channel_3:
    api_base_url: 
  channel_4:
    api_base_url: 
  channel_5:
    api_base_url: 
  channel_6:
    api_base_url: 
  channel_7:
    api_base_url: 

models:
  gpt-4o:
    provider: openai
    name: gpt-4o-2024-08-06
    temperature: 0.0
    input_cost: 0.0025
    output_cost: 0.0125
    max_turns: 1
    max_tokens: 2048
  gpt-4.1:
    provider: openai
    name: gpt-4.1-2025-04-14
    temperature: 0.0
    input_cost: 0.002 ## Cost per 1k input tokens
    output_cost: 0.008 ## Cost per 1k output tokens
    max_turns: 1
    max_tokens: 2048
  claude-3-5-sonnet:
    provider: amazon
    name: "anthropic.claude-3-5-sonnet-20241022-v2:0"
    temperature: 0.0
    input_cost: 0.003
    output_cost: 0.015
    max_turns: 1
    max_tokens: 2048
  gemini-2.5-flash:
    provider: google
    name: "models/gemini-2.5-flash"
    temperature: 0.0
    input_cost: 0.0003 ## Cost per 1k input tokens
    output_cost: 0.0025 ## Cost per 1k output tokens
    max_turns: 1
    max_tokens: 2048
  gemini-2.5-pro:
    provider: google
    name: "models/gemini-2.5-pro"
    temperature: 0.0
    input_cost: 0.00125 ## Cost per 1k input tokens
    output_cost: 0.01 ## Cost per 1k output tokens
    max_turns: 1
    max_tokens: 2048
