agent_type: single_replication

benchmark_dir: ../dataset/benchmarks/replication_gt
results_dir: ../dataset/results/replication_gen/single_canvas
batches_config_path: ../dataset/batches/replication/batches.yaml

channels:
  channel_1:
    api_base_url: http://localhost:3006
  channel_2:
    api_base_url: http://localhost:3007
  channel_3:
    api_base_url: http://localhost:3008
  channel_4:
    api_base_url: http://localhost:3009
  channel_5:
    api_base_url: http://localhost:3010
  channel_6:
    api_base_url: 

models:
  gpt-4o:
    provider: openai
    name: gpt-4o-2024-08-06
    temperature: 0.0
    input_cost: 0.0025
    output_cost: 0.0125
    max_turns: 1
    max_tokens: 4096
  gpt-4.1:
    provider: openai
    name: gpt-4.1-2025-04-14
    temperature: 0.0
    input_cost: 0.002 ## Cost per 1k input tokens
    output_cost: 0.008 ## Cost per 1k output tokens
    max_turns: 1
    max_tokens: 32768
  o3:
    provider: openai
    name: o3-mini-2024-07-18
    temperature: 0.0
    input_cost: 0.00015
    output_cost: 0.0006
    max_turns: 1
    max_tokens: 4096
  claude-3-5-sonnet:
    provider: anthropic
    name: "anthropic.claude-3-5-sonnet-20241022-v2:0"
    temperature: 0.0
    input_cost: 0.003
    output_cost: 0.015
    max_turns: 1
    max_tokens: 8192
  gemini-2.5-flash:
    provider: google
    name: "models/gemini-2.5-flash"
    temperature: 0.0
    input_cost: 0.0003 ## Cost per 1k input tokens
    output_cost: 0.0025 ## Cost per 1k output tokens
    max_turns: 1
    max_tokens: 65536
  gemini-2.5-pro:
    provider: google
    name: "models/gemini-2.5-pro"
    temperature: 0.0
    input_cost: 0.00125 ## Cost per 1k input tokens
    output_cost: 0.01 ## Cost per 1k output tokens
    max_turns: 1
    max_tokens: 65536