name: canvaseval
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - aiohappyeyeballs=2.4.4=py311h06a4308_0
  - aiohttp=3.11.10=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alsa-lib=1.2.14=h5eee18b_0
  - aom=3.6.0=h6a678d5_0
  - arrow-cpp=19.0.0=h865e1df_2
  - attr=2.5.1=h166bdaf_1
  - attrs=24.3.0=py311h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=openblas
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotlicffi=1.0.9.2=py311h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=he5ede1b_6
  - certifi=2025.6.15=py311h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cccl=12.9.27=0
  - cuda-cccl_linux-64=12.9.27=0
  - cuda-crt-dev_linux-64=12.9.41=0
  - cuda-crt-tools=12.9.41=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cudart-dev_linux-64=12.9.79=0
  - cuda-cudart-static_linux-64=12.9.79=0
  - cuda-cudart_linux-64=12.9.79=0
  - cuda-cuobjdump=12.9.82=1
  - cuda-cupti=12.4.127=0
  - cuda-driver-dev_linux-64=12.9.79=0
  - cuda-libraries=12.4.1=0
  - cuda-nvcc=12.9.41=0
  - cuda-nvcc-dev_linux-64=12.9.41=0
  - cuda-nvcc-impl=12.9.41=0
  - cuda-nvcc-tools=12.9.41=0
  - cuda-nvcc_linux-64=12.9.41=0
  - cuda-nvdisasm=12.9.88=1
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-nvvm-dev_linux-64=12.9.41=0
  - cuda-nvvm-impl=12.9.41=0
  - cuda-nvvm-tools=12.9.41=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.9=3
  - cudnn=9.10.2.21=h2b6041c_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - datasets=2.14.4=pyhd8ed1ab_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - deprecated=1.2.13=py311h06a4308_0
  - dill=0.3.7=py311h06a4308_0
  - double-conversion=3.3.1=h6a678d5_0
  - eigen=3.4.0=hdb19cb5_0
  - expat=2.7.0=h5888daf_0
  - ffmpeg=6.1.1=h2a67f75_3
  - filelock=3.17.0=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freeglut=3.4.0=h8b03031_1
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.5.0=py311h5eee18b_0
  - fsspec=2025.5.1=py311he3bba80_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gdk-pixbuf=2.42.10=h64b468e_2
  - geos=3.13.1=h97f6797_0
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - huggingface_hub=0.31.2=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - imageio=2.37.0=py311h06a4308_0
  - importlib-metadata=8.5.0=py311h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jasper=4.2.4=h84def66_1
  - jinja2=3.1.6=py311h06a4308_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py311h06a4308_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - level-zero=1.23.0=h84d6215_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libaec=1.1.3=h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcap=2.75=h39aace5_0
  - libclang13=17.0.6=default_h97e9c88_4
  - libcublas=12.4.5.8=0
  - libcudnn=9.10.2.21=h24322f0_0
  - libcudnn-dev=9.10.2.21=h2b6041c_0
  - libcufft=11.2.1.3=0
  - libcufile=1.14.1.1=4
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.10.19=0
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=15.1.0=h767d61c_3
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglu=9.0.3=h60c0c69_1
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.1.0=h767d61c_3
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm17=17.0.6=h0ad199c_4
  - libllvm19=19.1.7=he89c38a_1
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmlir19=19.1.7=hdb19cb5_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvfatbin=12.9.82=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.29=ha39b09d_0
  - libopencv=4.10.0=h06a4308_5
  - libopenvino=2025.0.0=hdc3f47d_3
  - libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-auto-plugin=2025.0.0=h4d9b6c2_3
  - libopenvino-hetero-plugin=2025.0.0=h981d57b_3
  - libopenvino-intel-cpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-gpu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-intel-npu-plugin=2025.0.0=hdc3f47d_3
  - libopenvino-ir-frontend=2025.0.0=h981d57b_3
  - libopenvino-onnx-frontend=2025.0.0=h0e684df_3
  - libopenvino-paddle-frontend=2025.0.0=h0e684df_3
  - libopenvino-pytorch-frontend=2025.0.0=h5888daf_3
  - libopenvino-tensorflow-frontend=2025.0.0=h684f15b_3
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_3
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - librsvg=2.56.3=hb0330b6_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtheora=1.1.1=h7f8727e_3
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libtorch=2.5.1=gpu_cuda124_he07d216_204
  - libudev1=257.7=hbe16f8c_0
  - libunwind=1.6.2=h9c3ff4c_0
  - liburing=2.10=h84d6215_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=hfdd30dd_0
  - lit=19.1.7=py311h06a4308_1
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.7.1=h9153a54_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - mkl=2025.0.0=hacee8c2_941
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.1.0=py311h5eee18b_0
  - multiprocess=0.70.15=py311h06a4308_0
  - mysql=8.4.0=h721767e_2
  - nccl=2.21.5.1=ha515578_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.4.2=py311h06a4308_0
  - nomkl=3.0=0
  - numexpr=2.10.1=py311hd28fd6d_0
  - numpy=2.3.1=py311h7610711_0
  - numpy-base=2.3.1=py311h150128d_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openblas=0.3.29=h06a4308_0
  - openblas-devel=0.3.29=ha39b09d_0
  - opencv=4.10.0=py311h32367a4_5
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.5.1=h7b32b05_0
  - opentelemetry-api=1.30.0=py311h06a4308_0
  - orc=2.1.1=hd396ef6_0
  - packaging=24.2=py311h06a4308_0
  - pandas=2.2.3=py311h6a678d5_0
  - pango=1.50.7=h668f713_2
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py311hac6e08b_1
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=h29eaf8c_0
  - propcache=0.3.1=py311h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.15=h3f63f65_0
  - py-opencv=4.10.0=h06a4308_5
  - pyarrow=19.0.0=py311h6a678d5_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.11=he870216_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py311h5eee18b_0
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=gpu_cuda124_py311h307a77b_204
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - qtbase=6.7.3=hdaa5aa8_0
  - rav1e=0.7.1=h8fae777_3
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py311h5eee18b_0
  - requests=2.32.4=py311h06a4308_0
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.5.3=py311h448de89_0
  - scikit-image=0.25.2=py311hc74f9fe_0
  - scikit-learn=1.6.1=py311h6a678d5_0
  - scipy=1.15.3=py311h5e4e545_0
  - sentence-transformers=5.0.0=pyhd8ed1ab_0
  - setuptools=72.1.0=py311h06a4308_0
  - shapely=2.1.1=py311h3dc67b8_0
  - six=1.17.0=py311h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - svt-av1=3.0.2=h5888daf_0
  - sympy=1.13.3=py311h06a4308_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tesseract=5.2.0=h6a678d5_2
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tifffile=2025.2.18=py311h06a4308_0
  - tk=8.6.14=h993c535_1
  - tokenizers=0.21.0=py311h5e3497e_0
  - torchaudio=2.5.1=py311_cu124
  - torchvision=0.20.1=cuda124py311ha0e159c_102
  - tqdm=4.67.1=py311h92b7b1e_0
  - transformers=4.53.0=pyhd8ed1ab_0
  - triton=3.1.0=cuda124py311hac27663_3
  - typing-extensions=4.12.2=py311h06a4308_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wayland=1.23.1=h3e06ad9_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - wrapt=1.17.0=py311h5eee18b_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxcursor=1.2.3=h9b100fa_0
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxscrnsaver=1.2.4=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py311h5eee18b_0
  - zipp=3.21.0=py311h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
prefix: /home/daeheon/miniconda3/envs/canvaseval
