models:
  - name: "models/gemini-2.5-flash"
    provider: "google"
    temperature: 0.0
    max_tokens: 65536
    input_cost: 0.0003 ## Cost per 1k input tokens
    output_cost: 0.0025 ## Cost per 1k output tokens
    max_turns: 100
  - name: "models/gemini-2.5-pro"
    provider: "google"
    temperature: 0.0
    max_tokens: 65536
    input_cost: 0.00125 ## Cost per 1k input tokens
    output_cost: 0.01 ## Cost per 1k output tokens
    max_turns: 100
  - name: "gpt-4.1-2025-04-14"
    provider: "openai"
    temperature: 0.0
    max_tokens: 32768
    input_cost: 0.002 ## Cost per 1k input tokens
    output_cost: 0.008 ## Cost per 1k output tokens
    max_turns: 100
  - name: "anthropic.claude-3-5-sonnet-20241022-v2:0"
    provider: "anthropic"
    temperature: 0.0
    max_tokens: 4096
    input_cost: 0.003
    output_cost: 0.015
    max_turns: 100
  - name: "gpt-4o-2024-08-06"
    provider: "openai"
    temperature: 0.0
    max_tokens: 4096
    input_cost: 0.0025
    output_cost: 0.0125
    max_turns: 100
agent_type: "react"
