name: canvasbench
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
      - annotated-types==0.6.0
      - async-timeout==4.0.3
      - attrs==24.3.0
      - boto3==1.38.11
      - botocore==1.38.11
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.8
      - distro==1.9.0
      - fastapi==0.112.2
      - frozenlist==1.5.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx-sse==0.4.0
      - idna==3.7
      - jinja2==3.1.6
      - jiter==0.6.1
      - jmespath==1.0.1
      - jsonpatch==1.33
      - jsonpointer==2.1
      - langchain==0.3.25
      - langchain-aws==0.2.22
      - langchain-core==0.3.58
      - langchain-openai==0.3.16
      - langchain-text-splitters==0.3.8
      - langgraph==0.4.2
      - langgraph-checkpoint==2.0.21
      - langgraph-prebuilt==0.1.8
      - langgraph-sdk==0.1.66
      - multidict==6.1.0
      - numpy==1.26.4
      - openai==1.77.0
      - orjson==3.10.14
      - packaging==24.2
      - pip==25.1
      - propcache==0.3.1
      - pycparser==2.21
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pydantic-settings==2.6.1
      - pygments==2.19.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - s3transfer==0.12.0
      - setuptools==78.1.1
      - shellingham==1.5.0
      - six==1.17.0
      - sniffio==1.3.0
      - sqlalchemy==2.0.39
      - sse-starlette==2.1.3
      - starlette==0.38.2
      - tenacity==9.0.0
      - tiktoken==0.9.0
      - tqdm==4.67.1
      - typer==0.15.3
      - typer-slim==0.15.3
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - uvicorn==0.32.1
      - wheel==0.45.1
      - yarl==1.18.0
      - zstandard==0.23.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.2.0
      - anyio==4.9.0
      - bottleneck==1.4.2
      - cachetools==5.5.2
      - docstring-parser==0.16
      - google-api-core==2.24.2
      - google-auth==2.40.1
      - google-cloud-aiplatform==1.92.0
      - google-cloud-bigquery==3.31.0
      - google-cloud-core==2.4.3
      - google-cloud-resource-manager==1.14.2
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-genai==1.14.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpc-google-iam-v1==0.14.2
      - grpcio==1.72.0rc1
      - grpcio-status==1.72.0rc1
      - httpx==0.28.1
      - langchain-google-vertexai==2.0.22
      - langchain-mcp-adapters==0.0.10
      - numexpr==2.10.2
      - proto-plus==1.26.1
      - protobuf==6.31.0rc2
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - rsa==4.9.1
      - shapely==2.1.0
      - validators==0.35.0
      - websockets==15.0.1